name: abetterme
description: ABetterMe fitness application.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  intl: ^0.16.1
  provider: ^4.0.4
  validators: ^2.0.0+1
  firebase_auth: ^0.15.5+2
  flutter_spinkit: "^4.1.2"
  shared_preferences: ^0.5.6+3
  firebase_database: ^3.1.3
  json_annotation: ^3.0.1
  flappy_search_bar: ^1.7.2
  fl_animated_linechart: ^1.1.3
  dropdown_formfield: ^0.1.2
  after_init: ^0.1.2
  flutter_launcher_icons: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
          style: italic
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
  assets:
    - assets/images/logo.png

flutter_icons:
  image_path: assets/images/logo.png
  android: true
  ios: true